name: lottery_predictor
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  html: ^0.15.4
  sqflite: ^2.3.2
  path: ^1.9.0
  path_provider: ^2.1.2
  onnxruntime: ^1.4.1
  synchronized: ^3.1.0
  fl_chart: ^0.66.2
  provider: ^6.1.1
  intl: ^0.19.0
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/data/history.csv